<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://projektangriff.de/eva/core/model" nsPrefix="eva">
  <eClassifiers xsi:type="ecore:EClass" name="EvaComponentFactoryMeta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceParameters" upperBound="-1"
        eType="#//EvaParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaComponentMeta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="factory" lowerBound="1"
        eType="#//EvaComponentMeta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryArguments" upperBound="-1"
        eType="#//EvaArgument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EvaParameterType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EvaParameterType">
    <eLiterals name="STRING"/>
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="DOUBLE" value="2"/>
    <eLiterals name="FLAG" value="3"/>
    <eLiterals name="CLASS" value="4" literal=""/>
    <eLiterals name="SELECTABLE_ONE" value="5"/>
    <eLiterals name="SELECTABLE_MANY" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//EvaParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
